insert into cateringservices.items values(4001, "Burger", "Veg", 20, 3, 3, NOW());
insert into cateringservices.items values(4002, "Sandwich", "Veg", 20, 3, 3, NOW());
insert into cateringservices.items values(4003, "Meal", "Veg", 20, 4, 2, NOW());
insert into cateringservices.items values(4004, "Cheese Burger", "Veg", 20, 4, 2, NOW());
insert into cateringservices.items values(4005, "Falafal", "Veg", 20, 3, 3, NOW());
insert into cateringservices.items values(4006, "Meat Sandwich", "NonVeg", 20, 4, 2, NOW());
insert into cateringservices.items values(4007, "SeaFood Fries", "NonVeg", 20, 4, 2, NOW());
insert into cateringservices.items values(4008, "Meat Burger", "NonVeg", 20, 4, 2, NOW());
insert into cateringservices.items values(4009, "Chicken Falafal", "NonVeg", 20, 4, 3, NOW());
insert into cateringservices.items values(4010, "Chicken Burger", "NonVeg", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4011, "Egg Salad", "Salads", 20, 4, 4, NOW());
insert into cateringservices.items values(4012, "Chicken Salad", "Salads", 20, 4, 3, NOW());
insert into cateringservices.items values(4013, "Veg Salad", "Salads", 20, 4, 4, NOW());
insert into cateringservices.items values(4014, "Fish Salad", "Salads", 20, 4, 4, NOW());
insert into cateringservices.items values(4015, "Ratatouille Salad", "Salads", 20, 4, 4, NOW()); 
insert into cateringservices.items values(4016, "Fiesta Mango Black Bean Quinoa Salad", "Salads", 20, 4, 3, NOW());
insert into cateringservices.items values(4017, "Macaroni Salad", "Salads", 20, 3, 3, NOW());
insert into cateringservices.items values(4018, "Carne Asada Flant Steak Salad", "Salads", 20, 5, 4, NOW());
insert into cateringservices.items values(4019, "Italian Pasta Salad", "Salads", 20, 3, 3, NOW());
insert into cateringservices.items values(4020, "Mexican Pasta Salad", "Salads", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4021, "Potato Salad", "Salads", 20, 2, 3, NOW());
insert into cateringservices.items values(4022, "Chopped Fiesta Garden Salad", "Salads", 20, 4, 4, NOW());
insert into cateringservices.items values(4023, "Bacon-stuffed Shell Salad", "Salads", 20, 5, 4, NOW());
insert into cateringservices.items values(4024, "Asian Chicken Salad", "Salads", 20, 4, 3, NOW());
insert into cateringservices.items values(4025, "Grilled Chicken & Veggie Pasta Salad", "Salads", 20, 5, 3, NOW()); 
insert into cateringservices.items values(4026, "Black Bean Quinoa Casserole", "Veg", 20, 4, 4, NOW());
insert into cateringservices.items values(4027, "Vegetable Polenta Kebobs With Chimchur", "Veg", 20, 5, 3, NOW());
insert into cateringservices.items values(4028, "Sweet and Sour Cripsy Tofu", "Veg", 20, 5, 4, NOW());
insert into cateringservices.items values(4029, "Masala Chickpea Buddha Bowl", "Veg", 20, 5, 4, NOW());
insert into cateringservices.items values(4030, "Pasta and Lentils", "Veg", 20, 4, 4, NOW()); 
insert into cateringservices.items values(4031, "Chessy Skillet Bean & Veggie Taco Meal", "Veg", 20, 5, 3, NOW());
insert into cateringservices.items values(4032, "One-Pot Vegetarina Enchilada Bowls", "Veg", 20, 5, 3, NOW());
insert into cateringservices.items values(4033, "Pasta Primavera with Sauteed Vegetables", "Veg", 20, 5, 4, NOW());
insert into cateringservices.items values(4034, "Roasted Red Bell Pepper Pasta", "Veg", 20, 4, 3, NOW());
insert into cateringservices.items values(4035, "Vegetarian Shepherd's Pie", "Veg", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4036, "Meat Balls", "NonVeg", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4037, "Baked Chicken with Curry Sauce", "NonVeg", 20, 4, 3, NOW());
insert into cateringservices.items values(4038, "Beef and Cabbage", "NonVeg", 20, 4, 2, NOW());
insert into cateringservices.items values(4039, "Healthy Chicken Fajitas", "NonVeg", 20, 5, 3, NOW());
insert into cateringservices.items values(4040, "Spicy Ground Turkey & Cabbage Stir Fry", "NonVeg", 20, 5, 3, NOW());
insert into cateringservices.items values(4041, "Authentic Carnitas - Pork", "NonVeg", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4042, "Chile Colorado Burritos", "NonVeg", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4043, "Thick and Cheesy Spaghetti Pie", "NonVeg", 20, 5, 3, NOW());
insert into cateringservices.items values(4044, "Gambas", "NonVeg", 20, 4, 4, NOW());
insert into cateringservices.items values(4045, "Bbq Roasted Pork with Sauce", "NonVeg", 20, 5, 3, NOW());
insert into cateringservices.items values(4046, "Low Carb Mexican Fajita Bowl", "NonVeg", 20, 5, 4, NOW());
insert into cateringservices.items values(4047, "Fish Tacos with Grapefruit & Avocado", "NonVeg", 20, 5, 4, NOW()); 
insert into cateringservices.items values(4048, "Keto Broccoli Cheese Soup", "Soup", 20, 5, 3, NOW());
insert into cateringservices.items values(4049, "Loaded Baked Potato Soup", "Soup", 20, 4, 2, NOW()); 
insert into cateringservices.items values(4050, "Spicy Chicken Pasta Soup", "Soup", 20, 5, 3, NOW()); 
insert into cateringservices.items values(4051, "Easy Egg Drop Soup", "Soup", 20, 3, 3, NOW());
insert into cateringservices.items values(4052, "Mediterranean Pear Cinnamon Squash Soup", "Soup", 20, 4, 4, NOW());
insert into cateringservices.items values(4053, "Vegetarian Lentil Tortilla Soup", "Soup", 20, 4, 3, NOW());
insert into cateringservices.items values(4054, "Creamy Chicken and Mushroom Soup", "Soup", 20, 5, 3, NOW());
insert into cateringservices.items values(4055, "Mexican Port and Bean Soup", "Soup", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4056, "Broccoli Cheese Soup", "Soup", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4057, "Cream of Spinach and Yam Soup", "Soup", 20, 5, 4, NOW()); 
insert into cateringservices.items values(4058, "Ham and Potato Soup", "Soup", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4059, "Lentil Vegetable Soup", "Soup", 20, 5, 4, NOW()); 
insert into cateringservices.items values(4060, "Chicken Gnocchi Soup", "Soup", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4061, "Chicken Soup", "Soup", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4062, "Broccoli Cheddar Ale Soup", "Soup", 20, 4, 4, NOW()); 
insert into cateringservices.items values(4063, "Fresh Summer Corn Soup", "Soup", 20, 3, 4, NOW()); 
insert into cateringservices.items values(4064, "Three Cheese Broccoli Soup", "Soup", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4065, "Quick Miso Soup", "Soup", 20, 3, 4, NOW()); 
insert into cateringservices.items values(4066, "Flourless Nutella Banana Bread", "Sides - Bread", 20, 2, 3, NOW()); 
insert into cateringservices.items values(4067, "Keto Bread", "Sides - Bread", 20, 2, 4, NOW()); 
insert into cateringservices.items values(4068, "Sourdough Bread", "Sides - Bread", 20, 2, 4, NOW());
insert into cateringservices.items values(4069, "Polenta Bread", "Sides - Bread", 20, 2, 4, NOW());
insert into cateringservices.items values(4070, "Garlic Pull Apart Bread", "Sides - Bread", 20, 3, 3, NOW());
insert into cateringservices.items values(4071, "Everyday Bread", "Sides - Bread", 20, 1, 3, NOW());
insert into cateringservices.items values(4072, "Blueberry Banana Bread with Almond Milk", "Sides - Bread", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4073, "Irish Brown Bread", "Sides - Bread", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4074, "Simple Amish White Bread", "Sides - Bread", 20, 2, 4, NOW()); 
insert into cateringservices.items values(4075, "Vegan Banana Nut Bread", "Sides - Bread", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4076, "Pina Colada Hawaiian Bread", "Sides - Bread", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4077, "Italian Bread", "Sides - Bread", 20, 2, 3, NOW()); 
insert into cateringservices.items values(4078, "Garlic Bread", "Sides - Bread", 20, 2, 4, NOW()); 
insert into cateringservices.items values(4079, "Feta Bread", "Sides - Bread", 20, 2, 3, NOW()); 
insert into cateringservices.items values(4080, "Milk Bread", "Sides - Bread", 20, 1, 2, NOW()); 
insert into cateringservices.items values(4081, "Herb Bread", "Sides - Bread", 20, 2, 4, NOW()); 
insert into cateringservices.items values(4082, "Jalapeno Cheese Bread", "Sides - Bread", 20, 2, 3, NOW()); 
insert into cateringservices.items values(4083, "French Bread", "Sides - Bread", 20, 2, 3, NOW());
insert into cateringservices.items values(4084, "Raspberry Jam", "Sides - Jam", 20, 2, 4, NOW()); 
insert into cateringservices.items values(4085, "Strawberry Jam", "Sides - Jam", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4086, "Watermelon Jam", "Sides - Jam", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4087, "Apricot Jam", "Sides - Jam", 20, 2, 3, NOW()); 
insert into cateringservices.items values(4088, "Hot Pepper Jam", "Sides - Jam", 20, 2, 4, NOW()); 
insert into cateringservices.items values(4089, "Mango Jam", "Sides - Jam", 20, 2, 3, NOW()); 
insert into cateringservices.items values(4090, "Apple Jam", "Sides - Jam", 20, 1, 2, NOW()); 
insert into cateringservices.items values(4091, "Mixed Fruit Jam", "Sides - Jam", 20, 2, 4, NOW()); 
insert into cateringservices.items values(4092, "Bourbon Peach Jam", "Sides - Jam", 20, 2, 3, NOW()); 
insert into cateringservices.items values(4093, "Peanut", "Sides - Jam", 20, 2, 3, NOW());
insert into cateringservices.items values(4094, "Peanut Butter Protein Shake", "Drinks", 20, 3, 4, NOW()); 
insert into cateringservices.items values(4095, "Cherry Limeade", "Drinks", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4096, "Mango Melon Smoothie", "Drinks", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4097, "Blueberry Spinach Smoothie", "Drinks", 20, 3, 3, NOW()); 
insert into cateringservices.items values(4098, "Vodka Moscow - Magic Mule", "Drinks", 20, 4, 3, NOW()); 
insert into cateringservices.items values(4099, "Green Hawaiian Cocktail", "Drinks", 20, 3, 4, NOW()); 
insert into cateringservices.items values(40100, "Boozy Sparkling Lemonade", "Drinks", 20, 3, 3, NOW());
insert into cateringservices.items values(40101, "Sugar-Free Ginger Lemonade", "Drinks", 20, 4, 5, NOW()); 
insert into cateringservices.items values(40102, "Raspberry Lime Smoothie", "Drinks", 20, 3, 3, NOW()); 
insert into cateringservices.items values(40103, "Black Lemonade", "Drinks", 20, 2, 4, NOW()); 
insert into cateringservices.items values(40104, "Black Coffee", "Drinks", 20, 2, 3, NOW());
insert into cateringservices.items values(40105, "Ice Tea", "Drinks", 20, 2, 3, NOW()); 
insert into cateringservices.items values(40106, "Lemonade", "Drinks", 20, 2, 4, NOW()); 
insert into cateringservices.items values(40107, "Lemongrass Ginger Tea with Cinnamon", "Drinks", 20, 3, 4, NOW()); 
insert into cateringservices.items values(40108, "Coco-cola", "Drinks", 20, 2, 2, NOW()); 
insert into cateringservices.items values(40109, "Sprite", "Drinks", 20, 2, 2, NOW());
insert into cateringservices.items values(40110, "Diet Cola", "Drinks", 20, 3, 3, NOW()); 